import { defineEnvVars } from '@sveltejs/kit/env';
import { building } from '$app/env';
import * as v from 'valibot';

const value = (v: string | Promise<string>) => v.pipeAsync(v.unknown(), v.transformAsync(() => v));

export const variables = defineEnvVars({
	GEMINI_API_KEY: { schema: v.optional(v.string(), ''), description: 'API Key for Gemini' },
	GOOGLE_CLIENT_ID: { schema: v.optional(v.string(), ''), description: 'Google Client ID' },
	GOOGLE_CLIENT_SECRET: { schema: v.optional(v.string(), ''), description: 'Google Client Secret' },
	GITHUB_CLIENT_ID: { schema: v.optional(v.string(), ''), description: 'GitHub Client ID' },
	GITHUB_CLIENT_SECRET: { schema: v.optional(v.string(), ''), description: 'GitHub Client Secret' },
	GITLAB_CLIENT_ID: { schema: v.optional(v.string(), ''), description: 'GitLab Client ID' },
	GITLAB_CLIENT_SECRET: { schema: v.optional(v.string(), ''), description: 'GitLab Client Secret' },
	BETTER_AUTH_URL: { schema: v.optional(v.string(), ''), description: 'URL for Better Auth' },
	PUBLIC_APP_NAME: { schema: v.optional(v.string(), ''), description: 'Public App Name' },
	PUBLIC_APP_URL: { schema: building ? v.optional(v.string(), '') : v.pipe(v.string(), v.url()), description: 'Public App URL' },
	BETTER_AUTH_SECRET: { schema: building ? v.optional(v.string(), '') : v.string(), description: 'Secret for Better Auth' },
	EMAIL_PROVIDER: { schema: v.optional(v.string(), ''), description: 'Email Provider' },
	SMTP_HOST: { schema: v.optional(v.string(), ''), description: 'SMTP Host' },
	SMTP_PORT: { schema: v.optional(v.string(), ''), description: 'SMTP Port' },
	SMTP_USER: { schema: v.optional(v.string(), ''), description: 'SMTP User' },
	SMTP_PASSWORD: { schema: v.optional(v.string(), ''), description: 'SMTP Password' },
	SMTP_FROM: { schema: v.optional(v.string(), ''), description: 'SMTP From Address' },
	RESEND_API_KEY: { schema: v.optional(v.string(), ''), description: 'Resend API Key' },
	STORAGE_PROVIDER: { schema: v.optional(v.string(), ''), description: 'Storage Provider' },
	LOCAL_STORAGE_PATH: { schema: v.optional(v.string(), ''), description: 'Local Storage Path' },
	PUBLIC_STORAGE_URL: { schema: v.optional(v.string(), ''), description: 'Public Storage URL' },
	R2_ACCOUNT_ID: { schema: v.optional(v.string(), ''), description: 'R2 Account ID' },
	R2_ACCESS_KEY_ID: { schema: v.optional(v.string(), ''), description: 'R2 Access Key ID' },
	R2_SECRET_ACCESS_KEY: { schema: v.optional(v.string(), ''), description: 'R2 Secret Access Key' },
	R2_BUCKET_NAME: { schema: v.optional(v.string(), ''), description: 'R2 Bucket Name' },
	R2_PUBLIC_URL: { schema: v.optional(v.string(), ''), description: 'R2 Public URL' },
	S3_REGION: { schema: v.optional(v.string(), ''), description: 'S3 Region' },
	S3_ACCESS_KEY_ID: { schema: v.optional(v.string(), ''), description: 'S3 Access Key ID' },
	S3_SECRET_ACCESS_KEY: { schema: v.optional(v.string(), ''), description: 'S3 Secret Access Key' },
	S3_BUCKET_NAME: { schema: v.optional(v.string(), ''), description: 'S3 Bucket Name' },
	S3_PUBLIC_URL: { schema: v.optional(v.string(), ''), description: 'S3 Public URL' },
	MAX_VIDEO_SIZE_MB: { schema: v.optional(v.string(), ''), description: 'Max Video Size MB' },
	ENABLE_SERVER_COMPRESSION: { schema: v.optional(v.string(), ''), description: 'Enable Server Compression' },
	VIDEO_THUMBNAIL_ENABLED: { schema: v.optional(v.string(), ''), description: 'Video Thumbnail Enabled' },
	STRIPE_SECRET_KEY: { schema: v.optional(v.string(), ''), description: 'Stripe Secret Key' },
	STRIPE_WEBHOOK_SECRET: { schema: v.optional(v.string(), ''), description: 'Stripe Webhook Secret' },
	STRIPE_PRO_PRICE_ID: { schema: v.optional(v.string(), ''), description: 'Stripe Pro Price ID' },
	STRIPE_TEAM_PRICE_ID: { schema: v.optional(v.string(), ''), description: 'Stripe Team Price ID' },
	PAYSTACK_SECRET_KEY: { schema: v.optional(v.string(), ''), description: 'Paystack Secret Key' },
	PAYSTACK_PRO_PLAN_CODE: { schema: v.optional(v.string(), ''), description: 'Paystack Pro Plan Code' },
	PAYSTACK_TEAM_PLAN_CODE: { schema: v.optional(v.string(), ''), description: 'Paystack Team Plan Code' },
	RATE_LIMIT_ENABLED: { schema: v.optional(v.string(), ''), description: 'Rate Limit Enabled' },
	RATE_LIMIT_MAX_REQUESTS: { schema: v.optional(v.string(), ''), description: 'Rate Limit Max Requests' },
	RATE_LIMIT_WINDOW_MS: { schema: v.optional(v.string(), ''), description: 'Rate Limit Window MS' },
	DATABASE_URL: { schema: building ? v.optional(v.string(), '') : v.string(), description: 'Database Connection String' }
});
